// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: pb/simple.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcServer_SayHello_FullMethodName     = "/pb.RpcServer/SayHello"
	RpcServer_ClientStream_FullMethodName = "/pb.RpcServer/ClientStream"
	RpcServer_ServerStream_FullMethodName = "/pb.RpcServer/ServerStream"
	RpcServer_BidiStream_FullMethodName   = "/pb.RpcServer/BidiStream"
)

// RpcServerClient is the client API for RpcServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcServerClient interface {
	// 简单 RPC
	SayHello(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Reply, error)
	// 客户端流
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Result, Reply], error)
	// 服务端流
	ServerStream(ctx context.Context, in *Result, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error)
	// 双向流
	BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Reply], error)
}

type rpcServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcServerClient(cc grpc.ClientConnInterface) RpcServerClient {
	return &rpcServerClient{cc}
}

func (c *rpcServerClient) SayHello(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, RpcServer_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServerClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Result, Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcServer_ServiceDesc.Streams[0], RpcServer_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_ClientStreamClient = grpc.ClientStreamingClient[Result, Reply]

func (c *rpcServerClient) ServerStream(ctx context.Context, in *Result, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcServer_ServiceDesc.Streams[1], RpcServer_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, Reply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_ServerStreamClient = grpc.ServerStreamingClient[Reply]

func (c *rpcServerClient) BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcServer_ServiceDesc.Streams[2], RpcServer_BidiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_BidiStreamClient = grpc.BidiStreamingClient[Result, Reply]

// RpcServerServer is the server API for RpcServer service.
// All implementations must embed UnimplementedRpcServerServer
// for forward compatibility.
type RpcServerServer interface {
	// 简单 RPC
	SayHello(context.Context, *Result) (*Reply, error)
	// 客户端流
	ClientStream(grpc.ClientStreamingServer[Result, Reply]) error
	// 服务端流
	ServerStream(*Result, grpc.ServerStreamingServer[Reply]) error
	// 双向流
	BidiStream(grpc.BidiStreamingServer[Result, Reply]) error
	mustEmbedUnimplementedRpcServerServer()
}

// UnimplementedRpcServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcServerServer struct{}

func (UnimplementedRpcServerServer) SayHello(context.Context, *Result) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedRpcServerServer) ClientStream(grpc.ClientStreamingServer[Result, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedRpcServerServer) ServerStream(*Result, grpc.ServerStreamingServer[Reply]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedRpcServerServer) BidiStream(grpc.BidiStreamingServer[Result, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method BidiStream not implemented")
}
func (UnimplementedRpcServerServer) mustEmbedUnimplementedRpcServerServer() {}
func (UnimplementedRpcServerServer) testEmbeddedByValue()                   {}

// UnsafeRpcServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServerServer will
// result in compilation errors.
type UnsafeRpcServerServer interface {
	mustEmbedUnimplementedRpcServerServer()
}

func RegisterRpcServerServer(s grpc.ServiceRegistrar, srv RpcServerServer) {
	// If the following call pancis, it indicates UnimplementedRpcServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcServer_ServiceDesc, srv)
}

func _RpcServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcServer_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServerServer).SayHello(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcServer_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RpcServerServer).ClientStream(&grpc.GenericServerStream[Result, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_ClientStreamServer = grpc.ClientStreamingServer[Result, Reply]

func _RpcServer_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Result)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcServerServer).ServerStream(m, &grpc.GenericServerStream[Result, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_ServerStreamServer = grpc.ServerStreamingServer[Reply]

func _RpcServer_BidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RpcServerServer).BidiStream(&grpc.GenericServerStream[Result, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcServer_BidiStreamServer = grpc.BidiStreamingServer[Result, Reply]

// RpcServer_ServiceDesc is the grpc.ServiceDesc for RpcServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RpcServer",
	HandlerType: (*RpcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _RpcServer_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _RpcServer_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStream",
			Handler:       _RpcServer_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStream",
			Handler:       _RpcServer_BidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/simple.proto",
}
