// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: pb/simple.proto

package pb

import (
	pb_all_type "github.com/xiaogao688/zf-project/learn/grpc/interceptors/pb_all_type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Corpus int32

const (
	Corpus_UNIVERSAL Corpus = 0
	Corpus_WEB       Corpus = 1
	Corpus_IMAGES    Corpus = 2
	Corpus_LOCAL     Corpus = 3
	Corpus_NEWS      Corpus = 4
	Corpus_PRODUCTS  Corpus = 5
	Corpus_VIDEO     Corpus = 6
)

// Enum value maps for Corpus.
var (
	Corpus_name = map[int32]string{
		0: "UNIVERSAL",
		1: "WEB",
		2: "IMAGES",
		3: "LOCAL",
		4: "NEWS",
		5: "PRODUCTS",
		6: "VIDEO",
	}
	Corpus_value = map[string]int32{
		"UNIVERSAL": 0,
		"WEB":       1,
		"IMAGES":    2,
		"LOCAL":     3,
		"NEWS":      4,
		"PRODUCTS":  5,
		"VIDEO":     6,
	}
)

func (x Corpus) Enum() *Corpus {
	p := new(Corpus)
	*p = x
	return p
}

func (x Corpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Corpus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_simple_proto_enumTypes[0].Descriptor()
}

func (Corpus) Type() protoreflect.EnumType {
	return &file_pb_simple_proto_enumTypes[0]
}

func (x Corpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Corpus.Descriptor instead.
func (Corpus) EnumDescriptor() ([]byte, []int) {
	return file_pb_simple_proto_rawDescGZIP(), []int{0}
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_pb_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_pb_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Snippets      []string               `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`             // 数组
	Corpus        Corpus                 `protobuf:"varint,4,opt,name=corpus,proto3,enum=pb.Corpus" json:"corpus,omitempty"` // 枚举
	AllTypes      *pb_all_type.AllTypes  `protobuf:"bytes,5,opt,name=all_types,json=allTypes,proto3" json:"all_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pb_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pb_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *Result) GetCorpus() Corpus {
	if x != nil {
		return x.Corpus
	}
	return Corpus_UNIVERSAL
}

func (x *Result) GetAllTypes() *pb_all_type.AllTypes {
	if x != nil {
		return x.AllTypes
	}
	return nil
}

var File_pb_simple_proto protoreflect.FileDescriptor

const file_pb_simple_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/simple.proto\x12\x02pb\x1a\x1apb_all_type/all_type.proto\"\x19\n" +
	"\x05Reply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x9e\x01\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1a\n" +
	"\bsnippets\x18\x03 \x03(\tR\bsnippets\x12\"\n" +
	"\x06corpus\x18\x04 \x01(\x0e2\n" +
	".pb.CorpusR\x06corpus\x122\n" +
	"\tall_types\x18\x05 \x01(\v2\x15.pb_all_type.AllTypesR\ballTypes*Z\n" +
	"\x06Corpus\x12\r\n" +
	"\tUNIVERSAL\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\n" +
	"\n" +
	"\x06IMAGES\x10\x02\x12\t\n" +
	"\x05LOCAL\x10\x03\x12\b\n" +
	"\x04NEWS\x10\x04\x12\f\n" +
	"\bPRODUCTS\x10\x05\x12\t\n" +
	"\x05VIDEO\x10\x062\xa9\x01\n" +
	"\tRpcServer\x12!\n" +
	"\bSayHello\x12\n" +
	".pb.Result\x1a\t.pb.Reply\x12'\n" +
	"\fClientStream\x12\n" +
	".pb.Result\x1a\t.pb.Reply(\x01\x12'\n" +
	"\fServerStream\x12\n" +
	".pb.Result\x1a\t.pb.Reply0\x01\x12'\n" +
	"\n" +
	"BidiStream\x12\n" +
	".pb.Result\x1a\t.pb.Reply(\x010\x01B7Z5github.com/xiaogao688/zf-project/learn/grpc/buf/pb;pbb\x06proto3"

var (
	file_pb_simple_proto_rawDescOnce sync.Once
	file_pb_simple_proto_rawDescData []byte
)

func file_pb_simple_proto_rawDescGZIP() []byte {
	file_pb_simple_proto_rawDescOnce.Do(func() {
		file_pb_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_simple_proto_rawDesc), len(file_pb_simple_proto_rawDesc)))
	})
	return file_pb_simple_proto_rawDescData
}

var file_pb_simple_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_simple_proto_goTypes = []any{
	(Corpus)(0),                  // 0: pb.Corpus
	(*Reply)(nil),                // 1: pb.Reply
	(*Result)(nil),               // 2: pb.Result
	(*pb_all_type.AllTypes)(nil), // 3: pb_all_type.AllTypes
}
var file_pb_simple_proto_depIdxs = []int32{
	0, // 0: pb.Result.corpus:type_name -> pb.Corpus
	3, // 1: pb.Result.all_types:type_name -> pb_all_type.AllTypes
	2, // 2: pb.RpcServer.SayHello:input_type -> pb.Result
	2, // 3: pb.RpcServer.ClientStream:input_type -> pb.Result
	2, // 4: pb.RpcServer.ServerStream:input_type -> pb.Result
	2, // 5: pb.RpcServer.BidiStream:input_type -> pb.Result
	1, // 6: pb.RpcServer.SayHello:output_type -> pb.Reply
	1, // 7: pb.RpcServer.ClientStream:output_type -> pb.Reply
	1, // 8: pb.RpcServer.ServerStream:output_type -> pb.Reply
	1, // 9: pb.RpcServer.BidiStream:output_type -> pb.Reply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_simple_proto_init() }
func file_pb_simple_proto_init() {
	if File_pb_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_simple_proto_rawDesc), len(file_pb_simple_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_simple_proto_goTypes,
		DependencyIndexes: file_pb_simple_proto_depIdxs,
		EnumInfos:         file_pb_simple_proto_enumTypes,
		MessageInfos:      file_pb_simple_proto_msgTypes,
	}.Build()
	File_pb_simple_proto = out.File
	file_pb_simple_proto_goTypes = nil
	file_pb_simple_proto_depIdxs = nil
}
