// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: pb_all_type/all_type.proto

package pb_all_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 双精度浮点数，对应 Go float64
	DoubleField float64 `protobuf:"fixed64,1,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	// 单精度浮点数，对应 Go float32
	FloatField float32 `protobuf:"fixed32,2,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	// 可变长度编码的 32 位有符号整数
	Int32Field int32 `protobuf:"varint,3,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	// 可变长度编码的 64 位有符号整数
	Int64Field int64 `protobuf:"varint,4,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	// 可变长度编码的 32 位无符号整数
	Uint32Field uint32 `protobuf:"varint,5,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	// 可变长度编码的 64 位无符号整数
	Uint64Field uint64 `protobuf:"varint,6,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	// 可变长度编码的 32 位有符号整数，使用 ZigZag 编码提高负数效率
	Sint32Field int32 `protobuf:"zigzag32,7,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	// 可变长度编码的 64 位有符号整数，使用 ZigZag 编码提高负数效率
	Sint64Field int64 `protobuf:"zigzag64,8,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	// 固定长度 4 字节的无符号整数，常用于值范围已知的小整数
	Fixed32Field uint32 `protobuf:"fixed32,9,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	// 固定长度 8 字节的无符号整数，常用于值范围已知的大整数
	Fixed64Field uint64 `protobuf:"fixed64,10,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	// 固定长度 4 字节的有符号整数
	Sfixed32Field int32 `protobuf:"fixed32,11,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	// 固定长度 8 字节的有符号整数
	Sfixed64Field int64 `protobuf:"fixed64,12,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	// 布尔值，对应 Go bool
	BoolField bool `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	// UTF-8 编码的字符串，长度不超过 2^32-1
	StringField string `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	// 任意字节序列，长度不超过 2^32-1
	BytesField    []byte `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypes) Reset() {
	*x = AllTypes{}
	mi := &file_pb_all_type_all_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypes) ProtoMessage() {}

func (x *AllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_all_type_all_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypes.ProtoReflect.Descriptor instead.
func (*AllTypes) Descriptor() ([]byte, []int) {
	return file_pb_all_type_all_type_proto_rawDescGZIP(), []int{0}
}

func (x *AllTypes) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *AllTypes) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *AllTypes) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *AllTypes) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *AllTypes) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *AllTypes) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *AllTypes) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *AllTypes) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *AllTypes) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *AllTypes) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *AllTypes) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *AllTypes) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *AllTypes) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *AllTypes) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *AllTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

var File_pb_all_type_all_type_proto protoreflect.FileDescriptor

const file_pb_all_type_all_type_proto_rawDesc = "" +
	"\n" +
	"\x1apb_all_type/all_type.proto\x12\vpb_all_type\"\x97\x04\n" +
	"\bAllTypes\x12!\n" +
	"\fdouble_field\x18\x01 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x02 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x03 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x04 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x05 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x06 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\a \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\b \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\t \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\n" +
	" \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\v \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\f \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesFieldBIZGgithub.com/xiaogao688/zf-project/learn/grpc/buf/pb_all_type;pb_all_typeb\x06proto3"

var (
	file_pb_all_type_all_type_proto_rawDescOnce sync.Once
	file_pb_all_type_all_type_proto_rawDescData []byte
)

func file_pb_all_type_all_type_proto_rawDescGZIP() []byte {
	file_pb_all_type_all_type_proto_rawDescOnce.Do(func() {
		file_pb_all_type_all_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_all_type_all_type_proto_rawDesc), len(file_pb_all_type_all_type_proto_rawDesc)))
	})
	return file_pb_all_type_all_type_proto_rawDescData
}

var file_pb_all_type_all_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_all_type_all_type_proto_goTypes = []any{
	(*AllTypes)(nil), // 0: pb_all_type.AllTypes
}
var file_pb_all_type_all_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_all_type_all_type_proto_init() }
func file_pb_all_type_all_type_proto_init() {
	if File_pb_all_type_all_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_all_type_all_type_proto_rawDesc), len(file_pb_all_type_all_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_all_type_all_type_proto_goTypes,
		DependencyIndexes: file_pb_all_type_all_type_proto_depIdxs,
		MessageInfos:      file_pb_all_type_all_type_proto_msgTypes,
	}.Build()
	File_pb_all_type_all_type_proto = out.File
	file_pb_all_type_all_type_proto_goTypes = nil
	file_pb_all_type_all_type_proto_depIdxs = nil
}
